"""Changed tasks table_ds

Revision ID: 0669c63bc90b
Revises: 65757db3fc33
Create Date: 2025-05-08 01:27:03.608474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0669c63bc90b'
down_revision: Union[str, None] = '65757db3fc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_constraint('analyzes_lab_id_fkey', 'analyzes', type_='foreignkey')
    op.drop_column('analyzes', 'lab_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyzes', sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('analyzes_lab_id_fkey', 'analyzes', 'labs', ['lab_id'], ['id'])
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('free', 'booked', 'in_progress', 'completed', name='orderstatus'), server_default=sa.text("'free'::orderstatus"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analis_id'], ['analyzes.id'], name='orders_analis_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    # ### end Alembic commands ###
